### PR TITLE
Touch input device

### PR DESCRIPTION
**Pull request by rafaelcaricio**
Make it possible to recognize touch inputs from any pointer device (touchscreen/mouse/etc).

### CODE REVIEW

**Comment by Aidan-Chelig** [comment]
anything happening with this PR?

**Comment by rafaelcaricio** [comment]
@Aidan-Chelig probably not. Please read the notice at the top of the README: https://github.com/rafaelcaricio/lvgl-rs#-lvgl---open-source-embedded-gui-library-in-rust

**Comment by Aidan-Chelig** [comment]
Understood, awesome work regardless!

**Comment by rafaelcaricio** [comment]
@Aidan-Chelig you might be interested in the work done in #62

**Comment by nia-e** [comment]
All changes here were implemented in #62 so I think this can be closed :D

**Pull request closed without merging**
