### PR TITLE
Implement proper font support

### LINKED ISSUE #43: Improved custom font support
There is a new feature of LVGL C library that looks very cool on version [7.4.0](https://github.com/lvgl/lvgl/releases/tag/v7.4.0):
> Add lv_font_load() function - Loads a lv_font_t object from a binary font file
> Add lv_font_free() function - Frees the memory allocated by the lv_font_load() function

This would enable us to load a custom function completely safe.

### LINKED ISSUE #70: Fix regression in font support
At some point in #51 we (I) accidentally broke font handling - mea culpa, sorry. We need to fix the broken APIs and also get started on #43 along with it

### PR DESCRIPTION
**Pull request by nia-e**
Goal of this PR is to enable support for custom fonts. This fixes #70 and closes #43. Current status and goals:
- [x] Support all builtin LVGL fonts
- [x] Support the C-encoded font that LVGL can generate
- [x] Document!
- [x] Go off-topic and bundle in a bunch of documentation additions and write a changelog apparently

### CODE REVIEW

**Comment by nia-e** [comment]
Currently I'm thinking of shipping the built-in LVGL fonts as nightly-only, since they depend on the `cfg_accessible` feature which isn't stable. I probably could write a proc macro to get this working otherwise, or move it into `lvgl_codegen` (since I can just read the constants defined in `lv_conf.h`). This would also enable `lv_drivers` being usable without macro spam (there were so many fonts here I couldn't justify the same kind of macro spam to myself...) However, I'll probably do that Later™️

**Comment by nia-e** [comment]
I tested out the idea of reverting #75 and reborrowing the pointer in `display.rs` as a `&mut T` but it did not seem to work and I think I get why. The body of the function makes relatively heavy use of typical rust references, and [mixing references and pointers does tend to be somewhat frowned upon](https://faultlore.com/blah/fix-rust-pointers/#references-make-really-strong-assertions), so I'm guessing we're causing UB somehow by simply accessing the LVGL display driver as a normal reference - regardless, moving out and back in seems to be fine and conceptually this makes sense as it enforces a hard limit between raw pointer land and reference land. I'd love to run miri on everything and be able to point a finger at the problem but alas miri doesn't support FFI, so in my opinion I'd say we should stick to this for now. It's a small enough copy that it shouldn't be a *huge* problem, as the deref only performs a shallow copy so it's just a few hundred bytes of pointers being copied.

**Comment by nia-e** [comment]
This is ready to be merged, just needs commits squashed. I added some docs to the driver usage as well. Let me know if I missed anything (and especially if you have better ideas for [this](https://github.com/rafaelcaricio/lvgl-rs/pull/76#issuecomment-1485823690))

**Comment by nia-e** [comment]
Also: the demo example works as intended again :D
image

**Comment by nia-e** [comment]
Squashed commits. This is ready to merge for real I promise I won't add any more documentation on this PR

**Comment by rafaelcaricio** [comment]
@nia-e feel free to merge your PRs. At this point I thrust, you know what you are doing, and I don't want to slow you down. 😉 I will be looking sporadically when I get some spare time.

**Review by rafaelcaricio — APPROVED** [review]

**Comment by nia-e** [comment]
Thanks so much, I really appreciate the trust :D I still need to request a review every time since I can't merge without an approval, though

**Comment by rafaelcaricio** [comment]
@nia-e You shouldn't need any more approvals to merge PRs now. PRs are still needed, but you should be able to merge them right away.

**Comment by nia-e** [comment]
Woo, thanks! I have another one I should be opening in a hot minute regarding #69

**Pull request merged**
